[package]
name = "buildtovalue-bindings"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "buildtovalue_governance"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true }
buildtovalue-kernel = { path = "../kernel" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true, optional = true }
sha2 = { workspace = true }
log = "0.4.29"          # <-- adicionado

[features]
default = ["python", "c"]
python = ["pyo3/extension-module"]
c = []

[package.metadata.maturin]
name = "buildtovalue_governance"