[package]
name = "buildtovalue-bindings"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "BuildToValue FFI Bindings for Python"
license.workspace = true

[lib]
name = "buildtovalue_governance"
crate-type = ["cdylib"]

[dependencies]
# Kernel com suporte a FFI ativado
buildtovalue-kernel = { path = "../kernel", features = ["ffi-bindings"] }

# Python FFI (Herdado do Workspace)
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py310"] }
prost = { workspace = true }

[features]
default = ["python"]
python = ["buildtovalue-kernel/ffi-bindings"]