[package]
name = "buildtovalue-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "btv"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
colored = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dotenv = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = []