[package]
name = "buildtovalue-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true }
colored = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }   # adicionado rt-multi-thread

[[bin]]
name = "btv"
path = "src/main.rs"