
use quickcheck::{quickcheck, TestResult, Arbitrary, Gen};
use buildtovalue::kernel::evidence::{TechnicalEvidence, Finding};
use buildtovalue::kernel::validators::{ValidatorModule, TechnicalSeverity};

#[derive(Clone, Debug)]
struct ArbitraryFinding(Finding);

impl Arbitrary for ArbitraryFinding {
    fn arbitrary(g: &mut Gen) -> Self {
        let modules = [
            ValidatorModule::CPF,
            ValidatorModule::CNPJ,
            ValidatorModule::CreditCard,
            ValidatorModule::Entropy,
            ValidatorModule::ZScore,
        ];
        
        let severities = [
            TechnicalSeverity::Low,
            TechnicalSeverity::Medium,
            TechnicalSeverity::High,
            TechnicalSeverity::PolicyViolation,
            TechnicalSeverity::Critical,
        ];
        
        let module = *g.choose(&modules).unwrap();
        let severity = *g.choose(&severities).unwrap();
        
        let finding = Finding::new(
            module,
            severity,
            "ARBITRARY_FINDING",
            "Generated by QuickCheck",
            "Random finding for property testing",
        );
        
        ArbitraryFinding(finding)
    }
}

quickcheck! {
    /// Property: Ring buffer nunca excede capacidade
    fn prop_ring_buffer_never_overflows(findings: Vec<ArbitraryFinding>) -> bool {
        let mut evidence = TechnicalEvidence::new(0x1234);
        
        for ArbitraryFinding(finding) in findings {
            evidence.add_finding(finding);
        }
        
        // Invariante: finding_count <= 10 AND critical_count <= 3
        evidence.finding_count <= 10 && evidence.critical_count <= 3
    }
    
    /// Property: Critical findings nunca são sobrescritos
    fn prop_critical_findings_preserved(
        normal_findings: Vec<ArbitraryFinding>,
        critical_count: u8
    ) -> TestResult {
        if critical_count > 3 {
            return TestResult::discard();
        }
        
        let mut evidence = TechnicalEvidence::new(0x1234);
        
        // Adiciona critical findings
        for _ in 0..critical_count {
            evidence.add_finding(Finding::new(
                ValidatorModule::CPF,
                TechnicalSeverity::Critical,
                "CRITICAL_TEST",
                "Critical",
                "...",
            ));
        }
        
        let initial_critical_count = evidence.critical_count;
        
        // Adiciona findings normais (tentativa de overflow)
        for ArbitraryFinding(finding) in normal_findings {
            if !finding.severity.is_critical() {
                evidence.add_finding(finding);
            }
        }
        
        // Critical count não deve mudar (preservado)
        TestResult::from_bool(evidence.critical_count == initial_critical_count)
    }
    
    /// Property: Ordem FIFO no ring buffer
    fn prop_ring_buffer_fifo_order(count: u8) -> TestResult {
        if count == 0 || count > 20 {
            return TestResult::discard();
        }
        
        let mut evidence = TechnicalEvidence::new(0x1234);
        
        // Adiciona findings numerados
        for i in 0..count {
            evidence.add_finding(Finding::new(
                ValidatorModule::Entropy,
                TechnicalSeverity::Low,
                &format!("FINDING_{:02}", i),
                "Test",
                "...",
            ));
        }
        
        // Se count > 10, apenas últimos 10 devem estar presentes
        if count > 10 {
            let findings = evidence.get_all_findings();
            let titles: Vec<String> = findings.iter()
                .map(|f| {
                    std::str::from_utf8(&f.title)
                        .unwrap()
                        .trim_end_matches('\0')
                        .to_string()
                })
                .collect();
            
            // Primeiros (count - 10) devem ter sido sobrescritos
            let first_expected = format!("FINDING_{:02}", count - 10);
            let last_expected = format!("FINDING_{:02}", count - 1);
            
            TestResult::from_bool(
                titles.contains(&last_expected) && 
                !titles.contains(&"FINDING_00".to_string())
            )
        } else {
            // Todos devem estar presentes
            TestResult::from_bool(evidence.finding_count == count)
        }
    }
}